# Generated by Django 4.2.10 on 2024-04-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register', '0005_remove_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='Register.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Register.userprofile')),
            ],
        ),
    ]
