# Generated by Django 4.2.10 on 2024-04-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_remove_customuser_profile_image'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='pending_followers',
            field=models.ManyToManyField(blank=True, related_name='pending_followers', to='Register.userprofile'),
        ),
    ]
