# Generated by Django 4.2.10 on 2024-04-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_remove_customuser_profile_image'),
        ('connections', '0002_connection_pending_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='Register.userprofile'),
        ),
    ]
