# Generated by Django 4.2.10 on 2024-04-19 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
    ]
