# Generated by Django 4.2.10 on 2024-06-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='title from terminal', max_length=55),
            preserve_default=False,
        ),
    ]
