# Generated by Django 4.2.10 on 2024-04-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
