# Generated by Django 4.2.10 on 2025-08-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_pollanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollanswer',
            name='answered_at',
        ),
    ]
