# Generated by Django 4.2.10 on 2025-08-08 06:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_remove_pollanswer_answered_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollanswer',
            old_name='user',
            new_name='votedby_user',
        ),
        migrations.AlterUniqueTogether(
            name='pollanswer',
            unique_together={('poll', 'votedby_user')},
        ),
    ]
