# Generated by Django 4.2.10 on 2024-06-06 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
                ('group_admins', models.ManyToManyField(related_name='group_admin', to=settings.AUTH_USER_MODEL)),
                ('join_requests', models.ManyToManyField(blank=True, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='group_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chats', to='group.customgroup')),
                ('receivers', models.ManyToManyField(related_name='received_group_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
