# Generated by Django 4.2.10 on 2024-04-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
