# Generated by Django 4.2.10 on 2024-04-24 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0005_alter_group_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CustomGroup',
        ),
    ]
