# Generated by Django 4.2.10 on 2024-04-24 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0006_rename_group_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='join_requests',
            field=models.ManyToManyField(blank=True, related_name='join_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
