# Generated by Django 4.2.10 on 2024-04-30 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0008_groupchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='receivers',
            field=models.ManyToManyField(related_name='received_group_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
