# Generated by Django 4.2.10 on 2024-05-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='scheduled_time',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
