# Generated by Django 4.2.10 on 2024-05-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='scheduled_time',
            field=models.DateTimeField(),
        ),
    ]
