# Generated by Django 4.2.10 on 2024-02-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_options_chatmessage_forwarded_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
