# Generated by Django 4.2.10 on 2024-05-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_scheduled_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='scheduled_time',
        ),
    ]
