# Generated by Django 4.2.10 on 2024-02-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='forwarded_from',
        ),
    ]
