# Generated by Django 4.2.10 on 2024-02-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_customuser_is_private'),
        ('chat', '0004_remove_chatmessage_forwarded_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='forwarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_messages', to='Register.userprofile'),
        ),
    ]
