# Generated by Django 4.2.10 on 2024-02-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage_forwarded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/'),
        ),
    ]
