# Generated by Django 4.2.10 on 2024-02-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
