# Generated by Django 4.2.10 on 2024-02-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatmessage_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
