# Generated by Django 4.2.10 on 2024-03-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatmessage_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='suggested_message',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
