# Generated by Django 4.2.10 on 2024-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatmessage_suggested_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
