# Generated by Django 4.2.10 on 2024-03-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatmessage_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='read',
        ),
    ]
