# Generated by Django 4.2.10 on 2024-02-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_customuser_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.URLField(default='exit', max_length=1024),
            preserve_default=False,
        ),
    ]
