# Generated by Django 4.2.10 on 2024-02-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
