# Generated by Django 4.2.10 on 2024-07-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_namechoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameChoice',
        ),
    ]
