# Generated by Django 4.2.10 on 2025-08-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0008_otprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
